version: "3.9"
services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: mchhub
      POSTGRES_PASSWORD: mchhub
      POSTGRES_DB: mchhub
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  backend:
    build: ./backend
    environment:
      DB_URL: jdbc:postgresql://db:5432/mchhub
      DB_USERNAME: mchhub
      DB_PASSWORD: mchhub
    depends_on:
      - db
    ports:
      - "8080:8080"
    volumes:
      - /Users/Alvin/Documents/mch/metacraft/:/Users/Alvin/Documents/mch/metacraft/
  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_BASE: http://localhost/api
        VITE_FILE_VIEWER_BASE: http://localhost/file-manager/
    depends_on:
      - backend
    ports:
      - "5173:80"
  file-manager-backend:
    #image: ghcr.io/alvinn8/ftp-client-backend:latest
    image: ftp-client-backend-local
    ports:
      - "8081:8081"
    volumes:
      - ./file-manager/extensions/:/app/server/extensions/:ro
  file-manager-frontend:
    #image: ghcr.io/alvinn8/ftp-client-frontend:latest
    image: ftp-client-frontend-local
    ports:
      - "9000:80"
    volumes:
      - ./file-manager/config.json:/usr/share/nginx/html/config.json:ro
    depends_on:
      - file-manager-backend
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
      - file-manager-frontend
      - file-manager-backend
volumes:
  db_data: